### ISSUE TITLE
Are the Python Bindings under development?

### ISSUE THREAD

**Issue by apacha** [rnpgp/py-rnp#1]
We think this project is really interesting and would like to use RNPGP. Given our current landscape, we would like to use it from Python. We came across this repository, but noted that it is completely empty. Are there any plans to implement such Python bindings in the near future?

**Comment by dewyatt** [comment]
Yes, unfortunately it hasn't been started yet. @ronaldtse Priority-wise where does this stand? It would pull me away from Confium, so maybe we should get someone else?

**Comment by ronaldtse** [comment]
@apacha as an update, @dewyatt has been hammering away on py-rnp the past few weeks and should have something ready soon. Thanks for the patience!

**Comment by apacha** [comment]
That sounds fantastic! Thanks for the update

**Comment by dewyatt** [comment]
Personal issues caused some delays, but an initial version has now been imported, so I think we can close this. :)
There is no documentation just yet but there is good test coverage that can be used as a reference.
