### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by dewyatt** [rnpgp/py-rnp#2]

**Comment by ronaldtse** [comment]
Added secret `RNP_PYPI_API_TOKEN`, can follow this GHA configuration: https://github.com/relaton/relaton-bib-py/blob/main/.github/workflows/release.yml

**Comment by ronaldtse** [comment]
@CAMOBAP would you be able to help with this? Thanks!

**Comment by CAMOBAP** [comment]
Done
